### PR TITLE
Add support for validating SDMX-ML v2.1 messages

### LINKED ISSUE #51: Validate SDMX-ML output using XSD
(Copied from the former [doc/roadmap.rst](https://github.com/khaeru/sdmx/blob/896eee2/doc/roadmap.rst).)

The schemas are available on GitHub:
https://github.com/sdmx-twg/sdmx-ml-v2_1/tree/master/schemas

This could be skipped by default, but provided as a public function (in e.g. `sdmx.format.xml`) and used in the test suite.

This would help guard against issues like #42.

### PR DESCRIPTION
**Pull request by goatsweater**
**Required:** write a single sentence that describes the changes made by this PR.

Add support for validating SDMX-ML messages via `sdmx.validate_xml()` (Closes #51)

### PR checklist
- [ ] Checks all ✅
- [ ] Update documentation
- [ ] Update doc/whatsnew.rst

### CODE REVIEW

**Comment by khaeru** [comment]
@goatsweater many thanks for the contribution here!

The test failures are due to added specimens for which the support is in #152. So for next steps:
- I will complete and merge that PR.
- I will ask you to rebase this branch on `main` (or I can do that if you don't feel comfortable).
- Once the checks pass, you can complete the PR description and checklist above.
- You can request a review from me.

…and then we will go from there.

I will also investigate the settings for this repo so I don't need to manually approve the CI runs on every push you (or other contributors) make to your branch.

**Comment by goatsweater** [comment]
@khaeru I saw that you had made some changes since my fork and merged those into this branch. I think that may have messed up the ability to rebase. I'm happy to close this and start over with a proper rebase if you'd like.

**Comment by khaeru** [comment]
> I think that may have messed up the ability to rebase. I'm happy to close this and start over with a proper rebase if you'd like.

If you don't mind, that would be appreciated. Please let me know if you get stuck and I can try to create a new branch by cherry-picking some commits from this one.

In the meantime I'll look at the CLA setup, as promised.

**Comment by goatsweater** [comment]
Closing in favor of #154

**Pull request closed without merging**
