### PR TITLE
Fallback to user-supplied DSD argument when reading XML

### PR DESCRIPTION
**Pull request by khaeru**
See discussion at https://github.com/khaeru/sdmx/issues/104#issuecomment-1305522794

### CODE REVIEW

**Comment by khaeru** [comment]
@miccoli are you able to/would you like to test the code on the branch to ensure it fixes the issue you identified at https://github.com/khaeru/sdmx/issues/104#issuecomment-1299035654?

If not, please just say so, and I'll go ahead and merge.

**Comment by miccoli** [comment]
@khaeru Yes, I'm able to test this PR: but right now I have very little free time, so please forgive me if I will look at the PR in a few days.

**Comment by khaeru** [comment]
No problem, thanks for your reply. Please just leave another comment when you have a chance to try the code.

**Comment by miccoli** [comment]
> No problem, thanks for your reply. Please just leave another comment when you have a chance to try the code.

@khaeru I just tried sdmx 2.7.0 with my scripts and everthing is working as expected! Thank you for the quick fix.

**Pull request merged**
