### PR TITLE
Add a new source for Statistics Lithuania; improve reader.sdmxml

### PR DESCRIPTION
**Pull request by bertrandmarc**
@khaeru please find attached firsts commits to start working on Issue #29.

### CODE REVIEW

**Comment by khaeru** [comment]
Excellent, thank you. I'll work on this branch to investigate the parsing issue we discussed.

**Comment by khaeru** [comment]
@bertrandmarc:
- Notice I corrected (1) the underline length in sources.rst, which must be at least as long as the title, and (2) startTime and endTime to startPeriod and endPeriod, because the former pair just return an error message.
- I do confirm the XML parse error with this code, so I can start to debug. Thanks!
- Is it correct that the 4 endpoints (categoryscheme, codelist, conceptscheme, and provisionagreement) are not supported by this source? (My Lithuanian isn't great :wink:) If so, we can mark that explicitly in sources.json.

**Comment by khaeru** [comment]
> - I do confirm the XML parse error with this code, so I can start to debug. Thanks!

Okay, now fixed in the last commit.

**Comment by khaeru** [comment]
Okay, aside from marking the non-supported endpoints, I think this is about complete.

**Comment by bertrandmarc** [comment]
@khaeru Indeed, according to the documentation (I can't read Lithuanian either, fortunately I get it in English), only data, datastructure, and dataflow are supported.

**Comment by khaeru** [comment]
Great, thanks. I'll address the remaining tests and then merge.

**Comment by khaeru** [comment]
The codecov/patch check failure is acceptable, because the new source-specific class lines will only be run as part of the nightly tests.

**Pull request merged**
