### PR TITLE
Add support for data availability queries

### PR DESCRIPTION
**Pull request by FedorYatsenko**
Add support for data availability queries (availableconstraint) defined by the [SDMX 2.1 standard](https://github.com/sdmx-twg/sdmx-rest/blob/v1.5.0/v2_1/ws/rest/docs/4_6_1_other_queries.md)

### CODE REVIEW

**Comment by khaeru** [comment]
Hi @FedorYatsenko —thanks for this contribution, much appreciated!

A couple of questions:
- Do you know any existing SDMX web services that will give responses to such queries?
- Can you give an example of code that uses this branch to query 1 or more of those services?

These would help me confirm the code works, and guide you in adding tests. Thanks in advance.

**Comment by FedorYatsenko** [comment]
Hi @khaeru,

I'm afraid, I can't yet share a link to SDMX web services that will give responses to such queries. As @sychsergiy mentioned in the khaeru/sdmx#164, our data provider is hidden by a private network.

Consequently, I'm not sure if this help you, but here is the code we are using: 
```
keys_dict = {
    'INDICATOR': ['PCPIHA_IX', 'PCPIHA_PC_CP_A_PT', 'PCPI_PC_CP_A_PT'],
    'COUNTRY':   ['111', '134'],
    'FREQUENCY': []
}
resp2 = sdmx_client.availableconstraint(
    'CPI',
    key=keys_dict,
    dsd=cpi_dsd
)
```
It generates the following link: `.../availableconstraint/CPI/111+134.PCPIHA_IX+PCPIHA_PC_CP_A_PT+PCPI_PC_CP_A_PT.*`.
And the following XML response: khaeru/sdmx-test-data#1

I am going to push a test for this file in this branch. Please let me know if I should change something.

**Comment by khaeru** [comment]
Thanks for adding the specimen in the other repo. On the next push the tests on this branch should find it.

I need to at some point add a PR template with a check-list for contributors. For now, while you're working on this draft, could you please:

1. Add a line to doc/whatsnew.rst, following the style of the existing entries.
2. Rebase the branch on the latest `main`, resolving any conflicts (don't need to do this repeatedly, only when ready to review/merge).

I'll come back to review when you indicate I should.

**Comment by FedorYatsenko** [comment]
Thank you for merging the specimen.

As for the whatsnew and updates to the latest main, I'll do that soon.

**Review by khaeru — APPROVED** [review]
Looks great! Thank you so much for this contribution.

At some point we should also extend the documentation to explain to users how to make data availability queries, like the example from your comment https://github.com/khaeru/sdmx/pull/161#issuecomment-1929361106

However since—as we've discussed—there aren't any known sources that support these, I'll make that a separate issue to be addressed later.

**Comment by FedorYatsenko** [comment]
Thank you very much for approving these changes.

**Comment by khaeru** [comment]
By the way: I see on the commit 31a7ba12b1f3f32df02d64cdbe4dba04e8c64687 that the associated username is "Fedir_Yatsenko", whereas your GitHub username appears to be "FedorYatsenko". I don't know why there is a mismatch (maybe difference between your local configuration and GitHub account), but as a result GitHub does not correctly associate the commit with your account, and you don't show up yet in the list of contributors: https://github.com/khaeru/sdmx/graphs/contributors 🥲 

I'm sorry for not noticing this earlier. I'll add a `:thanks:` to doc/whatsnew.rst when I prepare the next release.

**Comment by FedorYatsenko** [comment]
No worries. I just misspelled my name a little when creating my GitHub account.

**Pull request merged**
