### PR TITLE
Handle incorrect `CubeRegion`/`KeyValue` usage by IMF

### PR DESCRIPTION
**Pull request by khaeru**
This provides a narrowly-scoped workaround for #102.

### CODE REVIEW

**Comment by khaeru** [comment]
@zymon could you please try this branch and see if it resolves #102 for you?

You can install using pip directly from a git branch ([docs](https://pip.pypa.io/en/stable/topics/vcs-support/#git)), something like:
```
$ pip install sdmx1 @ git+https://github.com/khaeru/sdmx.git@issue/102
```

**Comment by zymon** [comment]
Hi Paul,
I tested your workaround on all IMF dataflows and it works well. Are you
going to release a new version of sdmx1 with this workaround?

The problem is indeed in the ContentConstraint element, so all the
dataflows that don't have the constraint work ok.
Here's the list of dataflows: ("failed" are the one that have the
constraint and don't work without your workaround)

success: ['5SR', 'BCG', 'BOP6', 'BOP_BPM6', 'BOP_GBPM6', 'BPM6_BOP_Q',
'BPM6_RA_M', 'CBS', 'CGD', 'CGD_GNA', 'CGO', 'CGO_GNA', 'COF', 'CPI',
'DCS', 'DSE_GBPM6', 'DSE_GNA', 'EMP', 'EXD', 'EXD_GBPM6', 'EXR',
'FAS_COLLECTION', 'FS1', 'FSI', 'GFC', 'GFG', 'GGD', 'GGD_GNA', 'GGO',
'GGO_GNA', 'GYQ', 'IIP5_COLLECTION', 'IIP6', 'IIP_BPM5', 'IIP_BPM6',
'IIP_GBPM6', 'ILV1', 'ILV1_GBPM6', 'ILV2', 'ILV2_GBPM6', 'INF', 'LMI',
'LMI_NSTD', 'MET', 'MSG', 'NAG', 'NAG_GNA', 'OFS', 'OFS_GNA', 'RTD', 'SBS',
'SBS_GNA', 'SOC', 'SPI', 'UEM', 'WOE', 'ZZZNL_TEST', 'ZZZ_TEST_ECOFIN']

failed: ['01R', '1DI', '1PI', '1SR', '2SR', '4SR', '60R', '6SR', '90R',
'BCGO_ALT_FISCAL', 'BOP5_COLLECTION', 'BOP_BPM5', 'CBS_NSTD',
'CGD_ALT_FISCAL', 'CGD_NSTD', 'CGO_ALT_FISCAL', 'CGO_NSTD', 'CPIH',
'DCS_NSTD', 'DOTS', 'DSE', 'EXD_BPM6', 'FLI', 'FS2', 'FSD', 'FSD_NSTD',
'GFB', 'GGD_ALT_FISCAL', 'GGO_ALT_FISCAL', 'IND', 'IND_NSTD', 'INR',
'INR_NSTD', 'MET_NSTD', 'NAG_08', 'NAG_93', 'NAG_NSTD', 'POP', 'PPI']

I sent info to the IMF, but it's a generic support email, so we'll need to
wait some time for their response.

Best regards,
Szymon

**Comment by khaeru** [comment]
Thanks for confirming and for the extra information. Now that you've done so, I'll merge this PR and indeed publish a new release—likely v2.6.4—in the next couple of days that will contain the workaround.

**Comment by zymon** [comment]
Great, thanks a lot!

**Pull request merged**
