### PR TITLE
Prepare and pass kwargs, including proxies, to requests.Session.send()

### LINKED ISSUE #26: HTTP[S]_PROXY environment variables appear to be ignored
It appears that HTTP_PROXY and HTTPS_PROXY variables are ignored by sdmx1, although they are taken into account by standard requests. If this is relevant, my proxy uses basic authication (HTTP_PROXY='http://user:pwd@proxyurl:port')

Please see the examples below:
```python
import sdmx
insee = sdmx.Request('INSEE')
insee.dataflow()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\sdmx\api.py", line 416, in get
    raise e from None
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\sdmx\api.py", line 413, in get
    response = self.session.send(req)
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bdm.insee.fr', port=443): Max retries exceeded with url: /series/sdmx/dataflow/ALL/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A886E2DA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

# However it works with manual configuration from the environment variables
from os import environ
insee = sdmx.Request('INSEE', proxies = {'http': environ['HTTP_PROXY'], 'https': environ['HTTPS_PROXY']})
insee.dataflow()
<sdmx.StructureMessage>
  <Header>
    id: 'dataflows_*_1605862772527'
    prepared: '2020-11-20T09:59:32.527000+01:00'
    receiver: <Agency unknown>
    sender: <Agency FR1: Institut national de la statistique et des études économiques>
    source: fr: Banque de données macro-économiques
    test: False
  response: <Response [200]>
  DataflowDefinition (212): BALANCE-PAIEMENTS CHOMAGE-TRIM-NATIONAL CLI...
  DataStructureDefinition (199): BALANCE-PAIEMENTS CHOMAGE-TRIM-NATIONA...

# It works without manual configuration with requests
import requests
requests.get('https://www.bdm.insee.fr/series/sdmx/dataflow/ALL/latest')
<Response [200]>
```

### PR DESCRIPTION
**Pull request by khaeru**
Closes #26.

## How to review

Attempt to make requests using an HTTP proxy.

### CODE REVIEW

**Comment by khaeru** [comment]
@bertrandmarc are you able to check out the git branch associated with this PR and attempt to run the same code as you showed in #26?

Some crude, manual testing on my end seems to indicate that an HTTP_PROXY environment variable makes it as far as this line: https://github.com/khaeru/sdmx/blob/8558a6d1a98c23bc285dba8dd264f10516cb4379/sdmx/api.py#L430-L431

…but, it would be good to know that an actual request can be completed through a proxy.

**Comment by bertrandmarc** [comment]
Hi @khaeru,

It took me a bit of time to test it properly, as I have very limited rights on the machine using a proxy. I finally managed, and it works both with and without requests-cache.

Thank you for fixing it!
Cheers,
Bertrand

```python
>>> import sdmx
>>> import pkg_resources
>>> pkg_resources.get_distribution('sdmx1').version
'1.5.1.dev2'
>>> insee = sdmx.Request('INSEE')
>>> insee.dataflow()
<sdmx.StructureMessage>
  <Header>
    id: 'dataflows_*_1606295315639'
    prepared: '2020-11-25T10:08:35.639000+01:00'
    receiver: <Agency unknown>
    sender: <Agency FR1: Institut national de la statistique et des études économiques>
    source: fr: Banque de données macro-économiques
    test: False
  response: <Response [200]>
  DataflowDefinition (210): BALANCE-PAIEMENTS CHOMAGE-TRIM-NATIONAL CLI...
  DataStructureDefinition (199): BALANCE-PAIEMENTS CHOMAGE-TRIM-NATIONA...

```

**Comment by bertrandmarc** [comment]
Sorry to come back on this. I have a naive question:
Why not rely on requests to do this instead of mimicking its behavior? Of course I don't get how everything are done in sdmx1, so my question might be stupid, but why overriding defaults with None at 
[https://github.com/khaeru/sdmx/blob/f19948dedc5a4dae2613ab007900f358d54185d2/sdmx/remote.py#L52:L55](https://github.com/khaeru/sdmx/blob/f19948dedc5a4dae2613ab007900f358d54185d2/sdmx/remote.py#L52:L55)

Cheers,
Bertrand

**Comment by khaeru** [comment]
Thank you for taking the time to check, and glad to hear it works!

> Why not rely on requests to do this instead of mimicking its behavior?

The short answer is: poor design choices in the pre-1.0 versions of pandaSDMX, prior to the fork to sdmx1.

See issue #11—this is a problem that's been recognized for a while. Making a better match with the semantics and class model of `requests` will reduce the need for duplication, workarounds, or copying, storing, etc. parameters (like the code you point to). However, it's a breaking change, and not a small one: it will require a bump from 1.x version number to 2.0, and adjustments in all the tests, and careful checking to ensure there's no regressions.

So, for now, this small fix.

**Pull request merged**
